name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'EOF'
            cd /var/www/chicmixt
            # Sauvegarde temporaire de la DB
            if [ -f prisma/dev.db ]; then
              mv prisma/dev.db /tmp/dev.db.temp
            fi
            git pull origin main
            # Restaure la DB
            if [ -f /tmp/dev.db.temp ]; then
              mv /tmp/dev.db.temp prisma/dev.db
            fi
            pnpm install
            pnpm prisma generate
            pnpm prisma migrate deploy
            pnpm run build
            pnpm run build:server
            npx pm2 restart ecosystem.config.js
          EOF